simple_model_configuration:
    figure_size: 300
    feature_map_sizes: [38, 19, 10, 5, 3, 1]
    steps: [8, 16, 32, 64, 100, 300]
    scales: [30, 60, 111, 162, 213, 264, 315]
    aspect_ratios: [(2,), (2,3), (2,3), (2,3), (2,), (2,)]
    feature_maps: [38, 19, 10, 5, 3, 1]