services:
  app:
    build: .
    shm_size: '2gb'
    tty: True
    ports:
      - "8000:5000"
    volumes:
      - .:/app
      - ../data:/data
    env_file:
    - path: .env
      required: false # default
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  wandb:
    image: wandb/local
    tty: True
    ports:
      - "8080:8080"
    volumes:
      - ./wandb:/vol  