version: "3.9"
services:
  app:
    build: .
    shm_size: '2gb'
    tty: True
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]