train: "/data/train.txt"
val: "/data/val.txt"
image_directory: "/data/JPEGImages"
annotation_directory: "/data/Annotations"
classes: ['aeroplane', 'bicycle', 'bird', 'boat', 'bottle', 'bus', 'car', 'cat', 'chair', 'cow', 'diningtable', 'dog', 'horse', 'motorbike', 'person', 'pottedplant', 'sheep', 'sofa', 'train', 'tvmonitor']