name: CI
on: [push]
jobs:
  check-formatting-compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        uses: ./.github/actions/docker-action
        with:
          command: "invoke lint"


      
